POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username": "haphung",
    "password": "12345"
}


###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username": "linhphan",
    "password": "54321"
}


###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username": "mienpham",
    "password": "abc"
}


###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username": "mienpham",
    "password": "abcdef"
}


###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "username": "yash",
    "password": "00001111"
}


### 
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "haphung",
    "password": "11111"
}


### 
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "haphung",
    "password": "12345"
}


###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "linhphan",
    "password": "12345"
}


###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "linhphan",
    "password": "12345"
}


###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "mienpham",
    "password": "12345"
}


###
POST http://localhost:3000/user/logout
Content-Type: application/json

{
}


###
POST http://localhost:3000/story
Content-Type: application/json

{
    "username": "haphung",
    "query": "smile happy umbrella"
}


###
POST http://localhost:3000/story
Content-Type: application/json

{
    "username": "linhphan",
    "query": "orange elephant monkey"
}


###
POST http://localhost:3000/story
Content-Type: application/json

{
    "username": "haphung",
    "query": ""
}


###
POST http://localhost:3000/story
Content-Type: application/json

{
    "username": "haphung",
}


