POST http://localhost:3000/generateVoice
Content-Type: application/json

{
    "prompt": "flower sky sea flower house cat dog"
}


###
POST http://localhost:3000/generateVoice
Content-Type: application/json

{
    "prompt": "Once upon a time, in a small town, there lived a bald man named Tim. Despite his lack of hair, Tim always had a cheerful demeanor, spreading smiles wherever he went. One day, a women's wrestling championship was held in town, and Tim couldn't resist the excitement. He decided to participate in a friendly match against a skilled wrestler. As the crowd cheered, Tim's opponent underestimated him, assuming his bald head would be a disadvantage. Little did they know, Tim's agility and determination made him a formidable competitor. With a smile on his face, Tim won the match, leaving the audience in awe and proving that appearances can be deceiving."
}
